server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive  # Required for Spring Cloud Gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway