server:
  port: 8083

spring:
  application:
    name: points-service
  datasource:
    url: jdbc:mysql://localhost:3306/goalapp_points
    username: D3_87069_Shubham
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: points-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      session-timeout-ms: 30000
      heartbeat-interval-ms: 3000
      max-poll-interval-ms: 300000
      properties:
        spring.json.trusted.packages: "org.goalapp.common.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      retry-backoff-ms: 1000
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000
      connections-max-idle-ms: 540000
      reconnect-backoff-ms: 50
      reconnect-backoff-max-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info
